### ISSUE TITLE
gprofiler installation

### ISSUE THREAD

**Issue by anay-broad** [mvinyard/ann_nmf#4]
Scanpy enrichment requires gprofiler-official to be installed; installing gprofiler as well conflicts with that and causes scanpy.queries.enrich() not to work.

**Comment by mvinyard** [comment]
I need to look into this. I don't know anything about `gprofiler`, so I am unsure of how involved this might be. If I can't get to it right away, I might suggest just running scanpy in a separate env. Will update here once I look into it and see if there's a fix.

**Comment by mvinyard** [comment]
@anay-broad gprofiler is a requirement of SignatureAnalyzer, which is upstream of this package. I'd recommend looking into a work-around on the Scanpy side of things.
